name: CratesPlus
description: A free and great crates plugin for Minecraft
main: com.connorlinfoot.cratesplus.CratesPlus
version: 1.3.1
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus,crates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op